// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Chokidar = require("chokidar");

function atomicCustom(ms) {
  return ms;
}

function watch(options, dir) {
  return Chokidar.watch(dir, options);
}

function watchMany(options, dirs) {
  return Chokidar.watch(dirs, options);
}

var atomicOn = true;

var atomicOff = false;

var awaitWriteFinishOn = true;

var awaitWriteFinishOff = false;

exports.atomicCustom = atomicCustom;
exports.atomicOn = atomicOn;
exports.atomicOff = atomicOff;
exports.awaitWriteFinishOn = awaitWriteFinishOn;
exports.awaitWriteFinishOff = awaitWriteFinishOff;
exports.watch = watch;
exports.watchMany = watchMany;
/* chokidar Not a pure module */
